language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "simmer-test";' -U postgres
script:
- npm run test-backend
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_54a65503014e_key -iv $encrypted_54a65503014e_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o "StrictHostKeyChecking no" simmer@simmer.brook.li 'bash ./simmer-deploy-master.sh'
  on:
    branch: deploy-test